server:
  port: 8080
  address: localhost
  tomcat:
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      force: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/conshare?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  thymeleaf:
    cache: false
    encoding: UTF-8
#    schema: import.sql

#mybatis:
#  mapper-locations: classpath:beldon/*.xml

banner:
  location: banner.txt
  charset: utf-8


